---
title: "Graphics with ggplot2"
author: "Javier Beltran"
date: "18 de noviembre de 2018"
output: html_document
---

```{r libraries, message=FALSE, warning=FALSE}
library(tidyverse)
```

# Learning ggplot2

We're learning ggplot2 It's going to be amazing. 

# Loading data

```{r}
#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```

# Readin the data

```{r}
head(ca)
```

#Our first ggplot graph

```{r}
ggplot(data=ca) +
  geom_point(aes(x = year, y = visitors))

#We get exactly the same result writing
ggplot(ca) +
  geom_point(aes(year,visitors))

```

